# Generated by Django 3.0.8 on 2020-07-27 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=20, verbose_name='NAME')),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100, verbose_name='PASSWORD')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='TITLE')),
                ('content', models.TextField(verbose_name='CONTENTS')),
                ('createdAt', models.DateField(auto_now_add=True, verbose_name='CREATEDAT')),
                ('updatedAt', models.DateField(auto_now=True, verbose_name='UPDATEDAT')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User')),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
    ]
